config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :users
  
  get "fieldnotes", :to => "notes#index"
  get "teamnotes", :to => "notes#team"
  
  # match "notes/:id/news", to: "notes#index", as: "fieldnotes", via: :get

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
end

app/controllers/smses_controller.rb
class SmsesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/smses_helper.rb
module SmsesHelper
end

app/views/home/index.html.erb
  <div class="multi-slider owl-carousel clearfix">
  	
	  <figure class="item"> <img data-src="assets/demo-images/113569013.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/dannypigart/113569013/">Danny PiG</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-sa/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/664637664.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/everydaylifemodern/664637664/">observista</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-nd/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/1383113606.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/asthmatic/1383113606/">asthmatic</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-nd/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/2033195014.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a class="text-underline" href="http://www.flickr.com/photos/pagedooley/2033195014/">kevin dooley</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/2191568652.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/karenhorton/2191568652/">karen horton</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/3210096256.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/ollieolarte/3210096256/">olarte.ollie</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-sa/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/4180676190.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/davefayram/4180676190/">DaveFayram</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by/2.0/">cc</a></figcaption>
	  </figure>
	  <figure class="item"> <img data-src="assets/demo-images/6995883979.jpg" src="#" alt="Feature 1" class="lazyOwl" />
	   <figcaption>credit: <a href="http://www.flickr.com/photos/chrispiascik/6995883979/">Chris Piascik</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-nd/2.0/">cc</a></figcaption>
	  </figure>
	  
  </div>

  <div class="banner">
	   <h1 class="display-text">
	   <span class="line-1">240<em>px</em> & Up</span> 
	   <span class="line-2">Responsive Wrapper</span> 
	   <span class="line-3">for Bootstrap 3x Framework</span>
	   </h1>
  </div>

  <h2 class="h1 font-weight-thin">Wrap & Roll sideWaze</h2>

  <p class="lead"><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget.</p>
  
  <div class="row">
  	
	   <div class="col-ms-6 col-sm-6">
	     <p>Pellentesque habitant morbi tristiquesenectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="index.html#" class="text-underline">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>
	   </div>
	   <div class="col-ms-6 col-sm-6">
	     <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo.</p>
	   </div>
	   
  </div>

  <hr class="vertical-spacer">
  
  <div class="row">
  	
     <div class="col-ms-4 col-sm-4">
	    <i class="fa fa-refresh feature-icon"><!--icon --></i>
	    <h2 class="spaced-out-header h4 uppercase font-weight-bold">Refreshing</h2>
	    <p class="med-sm">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.</p>
	    <p><a class="btn btn-default btn-sm" href="index.html#" role="button">Some Link &raquo;</a></p>
	    <hr class="vertical-spacer visible-xs">
     </div>
     <div class="col-ms-4 col-sm-4">
	    <i class="fa fa-mobile feature-icon"><!--icon --></i> <i class="fa fa-tablet feature-icon"><!--icon --></i> <i class="fa fa-desktop feature-icon"><!--icon --></i>
	    <h2 class="spaced-out-header h4 uppercase font-weight-bold">Responsive</h2>
	    <p class="med-sm">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.</p>
	    <p><a class="btn btn-default btn-sm" href="index.html#" role="button">Some Link &raquo;</a></p>
	    <hr class="vertical-spacer visible-xs">
     </div>
     <div class="col-ms-4 col-sm-4">
	    <i class="fa fa-code feature-icon"><!--icon --></i>
	    <h2 class="spaced-out-header h4 uppercase font-weight-bold">Clean</h2>
	    <p class="med-sm">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.</p>
	    <p><a class="btn btn-default btn-sm" href="index.html#" role="button">Some Link &raquo;</a></p>
     </div>
     
   </div>

  <hr class="vertical-spacer">
  
  <div class="row">
  	
     <div class="col-ms-5 col-sm-4 col-lg-5">
        <figure> 
        <img src="assets/demo-images/1383113606.jpg" class="img-responsive img-custom" alt="" />
        <figcaption class="small">credit: <a href="http://www.flickr.com/photos/asthmatic/1383113606/">asthmatic</a> via <a href="http://photopin.com">photopin</a> <a href="http://creativecommons.org/licenses/by-nd/2.0/">cc</a></figcaption>
        </figure>
        <hr class="vertical-spacer visible-xs"><!-- spacing vertically when stacked-->
     </div>
     <div class="col-ms-7 col-sm-8 col-lg-7">
	    <h2 class="h3 font-weight-thin no-margin-top">Head in the Game</h2>
	    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
	    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
	    <hr>
	    <blockquote>
	     <p class="lead">Design is not just what it looks like and feels like. Design is how it works.</p>
	     <footer>Steve Jobs </footer>
	    </blockquote>
     </div>
     
  </div>

app/views/layouts/_footer.html.erb
<div class="footer-content-1">
  <div class="inner-content">
   <h5>Hubungi Kami</h5>
   <p class="no-margin-bottom">
   <strong>Hasanah Consulting Group</strong><br>
   Jalan Mahakam Raya 19A<br>
   Bengkulu, BKS 38225<br>
   <strong>Phone:</strong> <a class="text-underline" href="tel:+6282233043298">+62 822 3304 3298</a><br><span class="overflow">
   <strong>Email:</strong> <a class="text-underline" href="mailto:consult@hasanah-consulting.com">consult@hasanah-consulting.com</a></span>
   </p>
   
  </div>
 </div>
 
 <hr class="divider">
 
 <div class="footer-content-2">
  <div class="inner-content">
   <h5>Layanan Bantuan IT Data Center</h5>
   <p>Layangkan Pertanyaan Anda kepada Kami. Tim IT Data Center Kami akan Membantu Anda.</p>
   <form action="http://bombdiggitydesign.com/wrap-n-roll/sidewaze/yourscript.php" method="post">
    <div class="input-group input-group-sm footer-signup">
     <input class="form-control" placeholder="Bagaimana hasil tabulasi suara?" type="text">
     <span class="input-group-btn">
     <button type="submit" class="btn btn-primary">Tanyakan</button>
     </span> 
    </div>
   </form>
  </div>
 </div>
 
 <hr class="divider">
 
 <div class="footer-content-3">
  <div class="inner-content">
   <h5>Gambar Kegiatan Terbaru</h5>
    <div class="img-widget clearfix">
        <a href="#"><img src="middle/assets/demo-images/florence-341469_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/frankfurt-285607_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/home-22527_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/milwaukee-art-museum-3984_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/reichstag-366201_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/stairs-8443_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/stairs-63747_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/stairs-113610_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/us-capitol-325341_150.jpg" alt="" /></a>
        <a href="#"><img src="middle/assets/demo-images/vaulted-cellar-247391_150.jpg" alt="" /></a>
    </div>
  </div>
 </div>
 
 <hr class="divider">
 <div class="footer-content-4">
  <div class="inner-content">
   <h5>Kabar Kampanye Terbaru</h5>
   <ul class="article-list"> 
    <li><a href="#">We will amplify our power to benchmark</a></li>
    <li><a href="#">We have revolutionized the conceptualization of structuring</a></li>
    <li><a href="#">Everything is relative; relatively speaking.</a></li>
    <li><a href="#">My other body is an immortal robot body.</a></li>
    <li><a href="#">I don't know who they are but they're right behind you</a></li>
    <li><a href="#">For those about to rock, we salute you </a> </li>
   </ul>
  </div>
 </div>
 
 <hr class="divider">
 <div class="inner-content copyright">
   <p class="small">© Copyright 2014 Hasanah Consulting Group. All rights reserved.</p>
 </div> 

app/views/layouts/_login_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>

<div class="modal-body">
  <div class="row">
	 <div class="col-sm-6 col-ms-6">
		<h4 class="title">Social Login</h4>
		<ul class="list-unstyled social-user">
		   <li><a href="#" title="Login with Facebook" class="facebook"><i class="fa fa-facebook"></i><span>Login with Facebook</span></a></li>
		   <li><a href="#" title="Login with Google Plus" class="google"><i class="fa fa-google-plus"></i><span>Login with Google</span></a></li>
	       <li><a href="#" title="Login with Twitter" class="twitter"><i class="fa fa-twitter"></i><span>Login with Twitter</span></a></li>
	       <li><a href="#" title="Login with Wordpress" class="wordpress"><i class="fa fa-wordpress"></i><span>Login with Wordpress</span></a></li>
	    </ul>
	 </div>
	 <div class="col-sm-6 col-ms-6">
		<h4 class="title">Sign In</h4>
		<form role="form" action="http://bombdiggitydesign.com/wrap-n-roll/sidewaze/your-login-script-goes-here.php">
		   <div class="form-group">
		      <input type="email" class="form-control" placeholder="Enter email">
		   </div>
		   <div class="form-group">
		      <input type="password" class="form-control" placeholder="Password">
		   </div>
		   <div class="form-group checkbox small">
		      <label>
		      <input type="checkbox">
		       Remember Me </label>
		   </div>
		   <p class="text-center">
		      <button class="btn btn-default btn-custom" type="submit"><i class="fa fa-lock"></i> Sign in</button>
		   </p>
		</form>
	 </div>
   
  </div> 
  <p class="text-center"><a class="text-underline" href="your-link-here.html">Forgot your password?</a><br>
  Don't have an account yet? <a class="text-underline" href="#signup-modal" data-toggle="modal" data-dismiss="modal">Sign up</a> </p>
</div>

app/views/layouts/_logo.html.erb
 <a href="#" class="toggle-menu"><i class="fa fa-bars"></i></a> 

 <div class="logo-wrapper">
  	<a href="#" class="clearfix"> <img id="logo" src="assets/images/logo.ori.png" alt="Hasanah Consulting group"> </a>
 </div>

 <div class="search-wrapper">
    <a href="#" class="toggle-search tooltip-hover" title="search" data-placement="left"><i class="fa fa-search"></i></a> 
  
    <div class="search-panel">
	   <form role="form">
	    <input type="search" placeholder="Enter search term and press enter" class="form-control">
	   </form>
    </div> 
 </div>

 <div class="social-wrapper">
   <ul>
	   <li><a href="#" class="fa fa-facebook tooltip-hover" data-placement="left" title="Follow Us on Facebook"></a></li>
	   <li><a href="#" class="fa fa-google-plus tooltip-hover" data-placement="left" title="Follow Us on Google Plus"></a></li>
	   <li><a href="#" class="fa fa-twitter tooltip-hover" data-placement="left" title="Follow Us on Twitter"></a></li>
	   <li><a href="#" class="fa fa-github tooltip-hover" data-placement="left" title="Visit our GitHub Page"></a></li>
	   <li><a href="#" class="fa fa-linkedin tooltip-hover" data-placement="left" title="Follow Us on LinkedIn"></a></li>
	   <li><a href="#" class="fa fa-instagram tooltip-hover" data-placement="left" title="Follow Us on Instagram"></a></li>
	   <li><a href="#" class="fa fa-rss tooltip-hover" data-placement="left" title="Subscribe to Our RSS Feed"></a></li>
   </ul>
 </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <nav id="nav" class="clearfix" role="navigation">
 
  <div class="user-wrapper">
   <p>
   	<a href="#login-modal" data-toggle="modal" class="toggle-login"> <i class="fa fa-sign-in"></i>&nbsp;&nbsp;Login</a> <span class="v-divider"></span> 
   	<a href="#signup-modal" data-toggle="modal" class="toggle-signup"> <i class="fa fa-pencil"></i>&nbsp;&nbsp;Sign Up</a>
   </p>
  </div>

  <ul class="primary-nav">   
	   <%= render 'layouts/navigation_links' %>
  </ul>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="active"><%= link_to 'Beranda', root_path %></li>
<li class="has-children"><a href="#">Strategi Kampanye</a>
  <ul>
	<li><%= link_to 'Jadwal Kampanye', root_path %></li>
	<li><%= link_to 'Peta Kampanye', root_path %></li>
	<li class="has-children"><a href="#">Distribusi Suara</a>
	  <ul>
		 <li><a href="#">Sukaraja</a></li>
		 <li><a href="#">Air Periukan</a></li>
		 <li><a href="#">Seluma Barat</a></li>
		 <li><a href="#">Semidang Alas Maras</a></li>
	  </ul></li>
    <li class="has-children"><a href="#">Daftar Tokoh</a>
	  <ul>
		 <li><a href="#">Sukaraja</a></li>
		 <li><a href="#">Air Periukan</a></li>
		 <li><a href="#">Seluma Barat</a></li>
		 <li><a href="#">Semidang Alas Maras</a></li>
	  </ul></li>
  </ul></li>
<li class="has-children"><%= link_to 'Catatan & Kronologi', root_path %>
  <ul>
	<li><%= link_to 'Berita Terbaru Daerah', root_path %></li>
	<li class="has-children"><%= link_to 'Kampanye Timses', root_path %>
	  <ul>
	    <li><a href="#">Sukaraja</a></li>
	    <li><a href="#">Air Periukan</a></li>
	  </ul></li>
	<li class="has-children"><%= link_to 'Anggota Timses', root_path %>
	  <ul>
	    <li><a href="#">Pengurus Harian</a></li>
	    <li><a href="#">Juru Kampanye</a></li>
	    <li><a href="#">Protokoler</a></li>
	    <li><a href="#">Public Relation (PR)</a></li>
	  </ul></li>
  </ul></li>
<li><%= link_to 'Field Notes', fieldnotes_path %></li>
<li><%= link_to 'Team Notes', teamnotes_path %></li>

app/views/layouts/_signup_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
</div>

<div class="modal-body">
  <div class="row">
   <div class="col-sm-6  col-ms-6">
	  <h4 class="title">Sign Up with...</h4>
	  <ul class="list-unstyled social-user">
	      <li><a href="#" title="Signup with Facebook" class="facebook"><i class="fa fa-facebook"></i><span>Signup with Facebook</span></a></li>
	      <li><a href="#" title="Signup with Google Plus" class="google"><i class="fa fa-google-plus"></i><span>Signup with Google</span></a></li>
	      <li><a href="#" title="Signup with Twitter" class="twitter"><i class="fa fa-twitter"></i><span>Signup with Twitter</span></a></li>
	      <li><a href="#" title="Signup with Wordpress" class="wordpress"><i class="fa fa-wordpress"></i><span>Signup with Wordpress</span></a></li>
	  </ul>
   </div>
   
   <div class="col-sm-6 col-ms-6">
	  <h4 class="title">Sign Up</h4>
	  <form role="form" action="http://bombdiggitydesign.com/wrap-n-roll/sidewaze/your-registrtation-script-goes-here.php">
	      <div class="form-group">
	        <input type="email" class="form-control" placeholder="Enter email">
	      </div>
	      <div class="form-group">
	        <input type="password" class="form-control" placeholder="Password">
	      </div>
	      <p class="text-center">
	        <button class="btn btn-default btn-custom" type="submit"><i class="fa fa-lock"></i> Register</button>
   	      </p>
	  </form>
   </div>
  </div>
  <p class="text-center">Already have an account? <a class="text-underline" href="#login-modal" data-toggle="modal" data-dismiss="modal">Login</a></p>
</div>

app/views/layouts/application.html.erb
<!--[if IE ]><![endif]-->
<!DOCTYPE html>
<!--[if lt IE 8]> <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="no-js lt-ie9 ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]> <html class="no-js lt-ie10 ie9" lang="en"> <![endif]-->
<!--[if (gte IE 10)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Master Vote" %>">
    <title><%= content_for?(:title) ? yield(:title) : "Master Vote" %></title>
	<link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="assets/css/bootstrap-modal.css" rel="stylesheet" type="text/css">
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Cinzel+Decorative' rel='stylesheet' type='text/css'> 
	<link href="assets/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css">
	<link href="assets/css/sidewaze_columns.css" rel="stylesheet" type="text/css">
	<link href="assets/css/sidewaze_base.css" rel="stylesheet" type="text/css">
	<link href="assets/css/colors/sidewaze_base_color.css" class="base-color" rel="stylesheet" type="text/css">
	<script src="assets/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
	<!--[if gt IE 8]><!-->
	<script src="assets/js/jquery.min.2.0.3.js"></script>
	<!--<![endif]-->
	<!--[if lt IE 9]>
	<script src="assets/js/1.9.1-jquery.min.js"></script>
	<![endif]-->
	<!-- WINDOWS 8 Phones BUG FIX -->
	<script src="assets/js/windows-fix.js"></script>
	<!--[if lt IE 9]>
	 <script type="text/javascript" src="assets/js/selectivizr.js"></script>
	<![endif]-->
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>


<body>

<ul class="sr-only" id="top">
 <li><a href="index.html#nav" title="Skip to navigation" accesskey="n">Skip to Navigation</a></li>
 <li><a href="index.html#page" title="Skip to content" accesskey="c">Skip to Content</a></li>
</ul>
 
<div class="nav-col">
<%= render 'layouts/navigation' %>
</div>
 
<div class="logo-col">
 <%= render 'layouts/logo' %>
</div>

<div class="content-col" id="page">
  <div class="inner-content" >
	  <%= render 'layouts/messages' %>
	  <%= yield %>
  </div>
</div>

<footer class="footer footer-col clearfix">
 <%= render 'layouts/footer' %>
</footer>

<div class="faux-col faux-nav-col"></div>
<div class="faux-col faux-logo-col"></div>
<div class="faux-col faux-content-col"></div>
<div class="faux-col faux-footer-col"></div>

<a id="go-to-top" title="up"> <i class="fa fa-arrow-circle-o-up"></i> </a> 

<div id="login-modal" class="modal fade user-modal" tabindex="-1" data-width="760" style="display: none;">
 <%= render 'layouts/login_modal' %>
</div>

<div id="signup-modal" class="modal fade user-modal" tabindex="-1" data-width="760" style="display: none;">
 <%= render 'layouts/signup_modal' %>
</div>

<script src="assets/js/bootstrap.min.js"></script> 
<script src="assets/js/jquery.sidewaze_base.js"></script> 
<script src="assets/js/bootstrap-modalmanager.js"></script> 
<script src="assets/js/bootstrap-modal.js"></script> 
<script src="assets/owl-carousel/owl.carousel.min.js"></script> 
<script>
     $(document).ready(function() {
        $(".multi-slider").owlCarousel({
        lazyLoad : true,
        navigation : false,
        pagination: true,
        items : 4, 
        itemsDesktop : [1400,4],
        itemsDesktopSmall : [900,3], 
        itemsTablet: [600,2], 
        itemsMobile : [320,1]
    });
 });
</script>

</body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>